name: Java CI with Maven and Docker

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@a5ac7e51b4109f5124f956403903c91b585df3a6 # v4.1.2
    - name: Set up JDK 21
      uses: actions/setup-java@b2314b3610f7936742435b5a41e414b7ba35a2a4 # v4.2.1
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

  Tests:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
    - name: Checkout code
      uses: actions/checkout@a5ac7e51b4109f5124f956403903c91b585df3a6 # v4.1.2
      with:
          fetch-depth: 0

    - name: Set up JDK 21
      uses: actions/setup-java@b2314b3610f7936742435b5a41e414b7ba35a2a4 # v4.2.1
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: 'maven'

    - name: Test and Verify with SonarQube
      run: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=rodfc773_cheffy-auth
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  Image-deploy:
    needs: Tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b4109f5124f956403903c91b585df3a6 # v4.1.2
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@b2314b3610f7936742435b5a41e414b7ba35a2a4 # v4.2.1
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'maven'

      - name: Login to Docker Hub
        uses: docker/login-action@e92390c5fb4206140f8094dcd7c058de44183f1b # v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@94ab15c0a11cec6b1805632595475529e1aa3540 # v5.3.0
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
